version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ../
      dockerfile: docker/dockerfile.frontend
    container_name: rafiky-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rafiky-network

  # Backend Service
  backend:
    build:
      context: ../
      dockerfile: docker/dockerfile.backend
    container_name: rafiky-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/rafiky
      - ADMIN_EMAIL=admin@rafiky.com
      - ADMIN_PASSWORD=Kobe824
      - NODE_ENV=production
    volumes:
      - backend-uploads:/app/uploads
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - rafiky-network

  # MongoDB Service
  mongodb:
    image: mongo:7-jammy
    container_name: rafiky-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=rafiky
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    restart: unless-stopped
    networks:
      - rafiky-network

# Volumes for persistent data
volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local
  backend-uploads:
    driver: local

# Network for service communication
networks:
  rafiky-network:
    driver: bridge
