# Multi-stage build for React Vite app

# Build stage
FROM node:18-alpine AS build

# Set working directory
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm i --legacy-peer-deps

# Copy source code
COPY frontend/ .

# Build the application
RUN npm run build


EXPOSE 5173

# Start the application
CMD ["npm", "run", "preview", "--", "--port", "5173", "--host", "0.0.0.0"]